# Generated by Django 2.1.3 on 2018-12-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la pelicula')),
                ('genero', models.CharField(max_length=30, verbose_name='Genero de la pelicula')),
                ('clasificacion', models.CharField(max_length=1, verbose_name='Clasificacion de la pelicula')),
                ('duracion', models.PositiveIntegerField(verbose_name='Duracion en minutos')),
                ('fecha_estreno', models.DateField(verbose_name='Fecha de estreno')),
                ('horario', models.TimeField(verbose_name='Horarios disponibles')),
                ('trailer', models.TextField(default='N/A', verbose_name='Trailer de la pelicula')),
                ('portada', models.TextField(verbose_name='Portada de la pelicula')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=10, verbose_name='Nombre de usuario')),
                ('contrasena', models.CharField(max_length=8, verbose_name='Contraseña')),
                ('cargo', models.CharField(max_length=20, verbose_name='Cargo de usuario')),
            ],
        ),
    ]
